### PR TITLE
NewPage with freeSpace extended #1648

### PR DESCRIPTION
**Pull request by 2S-Software**
New parameter 'freeSpace' to the existing widget [NewPage](https://pub.dev/documentation/pdf/3.10.8/widgets/NewPage-class.html) added, so that the page break is only executed if the free space is less than specified.

The default value of the new double parameter is Null, so that in this case a page break is always generated as before.

This PR solves the issue #1648.

### CODE REVIEW

**Comment by DavBfr** [comment]
What would be the reason to have newPageNeeded in the toplevel Widget?
It could be part of NewPage only or in a mixin.

**Comment by DavBfr** [comment]
But for backward compatibility, if someone created a method with this name it will break their app.

**Comment by 2S-Software** [comment]
> But for backward compatibility, if someone created a method with this name it will break their app.

I think the risk is low and would be easy to fix for the developer concerned. I believe the new options for other widgets are more important.

But your are the owner, you can decide...

**Comment by 2S-Software** [comment]
What can I do that all checks can be completed successfully and this PR can be merged?

**Comment by DavBfr** [comment]
I'll fix that.

**Comment by DavBfr** [comment]
Merged.

**Pull request closed without merging**
