### PR TITLE
Update document.dart

### PR DESCRIPTION
**Pull request by Gemy-Dev**
isolate it in another thread because it's freeze app

### CODE REVIEW

**Review by Gemy-Dev — COMMENTED** [review]
isolate save in another thread to solve freezing app

**Comment by DavBfr** [comment]
This library is compatible with Dart only (no Flutter) and Web.
This implementation won't work when built to JavaScript.

**Comment by Gemy-Dev** [comment]
using IsolateSave() method is solve freezing when save pdf file but it's not work for web

**Comment by Gemy-Dev** [comment]
using IsolatedSave() method is solve freezing when save pdf file but it's not work for web

**Comment by DavBfr** [comment]
OK, I'll make a version of that

**Pull request closed without merging**
