### PR TITLE
fix: Update ViewConfiguration to comply with Flutter `>=3.17.0-19.0.pre`

### PR DESCRIPTION
**Pull request by Gustl22**
The `size` parameter of ViewConfiguration does not exist any more in the latest Flutter master.

This is only a Draft PR to keep track of that issue. This doesn't necessarily be merged soon, as it needs bumping min Flutter version, when it will be released like that.

See: https://github.com/flutter/flutter/pull/138648/files#r1413066068
See: https://github.com/flutter/flutter/pull/138648

### CODE REVIEW

**Comment by Gustl22** [comment]
@DavBfr unfortunately they don't consider this change as breaking: https://github.com/flutter/flutter/pull/138648#discussion_r1414289667
I don't know a solution to that, but the pub resolver may solves this by only letting older versions to be installed compatible with the older Flutter releases, the other way around is more problematic, using a new Flutter release with the old dart_pdf plugin version installed.

**Comment by CrisNegoianu** [comment]
Hi. Thank you for the change.
This is now an issue on the beta channel.
Can this please be released?

**Comment by CrisNegoianu** [comment]
Maybe as a pre-release? that we can use until the flutter change make it to stable?

**Comment by Gustl22** [comment]
@DavBfr do you think it will be installed by pub, if it doesn't fulfill the min Flutter requirement (not sure, could be)? Or doing a major release.


@CrisNegoianu you can always use git dependecies:
```
dependencies:
  kittens:
    git:
      url: https://github.com/Gustl22/dart_pdf.git
      ref: patch-1
      path: printing
```

**Comment by CrisNegoianu** [comment]
Thanks for the suggestion.

**Comment by RoarGronmo** [comment]
Changing channel from `beta` to `main` may solve this issue for a while... ...so you can continue your work, if you cannot "roll back" to  stable.

**Comment by Gustl22** [comment]
@RoarGronmo they reverted the change in https://github.com/flutter/flutter/pull/140165
But they likely want to reland this change in the future, thus we can but must not leave it open.

**Comment by DavBfr** [comment]
Another PR fixes that.

**Comment by RoarGronmo** [comment]
Upgraded recently Flutter beta to 
```
[√] Flutter (Channel beta, 3.20.0-1.1.pre, on Microsoft Windows [Version 10.0.22631.3155], locale nb-NO)
    • Flutter version 3.20.0-1.1.pre on channel beta at c:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d7e373c6c2 (13 hours ago), 2024-02-15 11:34:03 -0800
    • Engine revision 9869d47a27
    • Dart version 3.4.0 (build 3.4.0-99.0.dev)
    • DevTools version 2.31.0
```
...and it seems to break again with:
```
[+12167 ms] /C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/printing-5.11.1/lib/src/widget_wrapper.dart:173:11: Error: No named parameter with the name 'size'.
[        ]           size:
[        ]           ^^^^
[        ] /c:/Flutter/flutter/packages/flutter/lib/src/rendering/view.dart:28:9: Context: Found this candidate, but the arguments don't match.
[        ]   const ViewConfiguration({
[        ]         ^^^^^^^^^^^^^^^^^
```

**Comment by RoarGronmo** [comment]
It breaks also in Flutter main channel this time:
```
[√] Flutter (Channel main, 3.20.0-7.0.pre.85, on Microsoft Windows [Version 10.0.22631.3155], locale nb-NO)
    • Flutter version 3.20.0-7.0.pre.85 on channel main at c:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a603a17875 (69 minutes ago), 2024-02-16 09:43:50 +0200
    • Engine revision dd530f1556
    • Dart version 3.4.0 (build 3.4.0-148.0.dev)
    • DevTools version 2.33.0-dev.6
```
so we are "stuck" in stable until resolved.

**Comment by sma** [comment]
I fixed it myself a few weeks ago, but I just checked and it looks like the master ist already fixed, so you probably only need to add a reference to the master repo to your `pubspec.yaml`, like for example (I haven't tested this):
```
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: 538cb6f
```

**Comment by RoarGronmo** [comment]
Thanx @sma, I'll check.

**Comment by RoarGronmo** [comment]
Somehow attempts to run `flutter bug get`, `flutter pub update` or `dart run build_runner build --delete-conflicting-outputs` fails with missing `pubspec.yaml` ...
```
PS C:\FlutterProjects\mOffice> flutter pub get
Resolving dependencies... (6.3s)
Could not find a file named "pubspec.yaml" in https://github.com/DavBfr/dart_pdf.git 538cb6fce96ff688658b8ad2f4725249b78472e6.
PS C:\FlutterProjects\mOffice> flutter pub upgrade
Resolving dependencies... (1.5s)
Could not find a file named "pubspec.yaml" in https://github.com/DavBfr/dart_pdf.git 538cb6fce96ff688658b8ad2f4725249b78472e6.
PS C:\FlutterProjects\mOffice> dart run build_runner build --delete-conflicting-outputs
Resolving dependencies in C:\FlutterProjects\mOffice... (1.0s)
Could not find a file named "pubspec.yaml" in https://github.com/DavBfr/dart_pdf.git 538cb6fce96ff688658b8ad2f4725249b78472e6.
```

So it didn't sort out for us..

**Comment by banjomss** [comment]
run `flutter pub add printing` to get latest. Ensure that pdf_widget_wrapper-1.0.4 is used and not 1.0.3 in pub.dev

**Comment by ReynaldoMaciel** [comment]
> run `flutter pub add printing` to get latest. Ensure that pdf_widget_wrapper-1.0.4 is used and not 1.0.3 in pub.dev

Thanks, readding the lib with ```flutter pub add printing``` solved here

**Pull request closed without merging**
