### PR TITLE
Add Noto Sans TC/SC fonts for traditional and simplified Chinese

### PR DESCRIPTION
**Pull request by minhdanh**
This PR adds two more Google Fonts:
- Noto Sans TC for traditional Chinese
- Noto Sans SC for simplified Chinese

### CODE REVIEW

**Comment by minhdanh** [comment]
I upgraded Java to version 17 and the CI passed on my side: https://github.com/minhdanh/dart_pdf/actions/runs/10536505834

**Comment by minhdanh** [comment]
Hi @DavBfr can you please check if the PR looks good?

**Comment by kevinetore** [comment]
Thank you for this feature!

@DavBfr, is there any chance you could create a release for this? Or is this already in the planning?

**Comment by minhdanh** [comment]
@kevinetore if you look at the changelog, this change already released: https://pub.dev/packages/printing/changelog

**Comment by kevinetore** [comment]
@minhdanh Thanks! I asked because I didn't see a new [GH tag](https://github.com/DavBfr/dart_pdf/tags).

**Pull request merged**
