### PR TITLE
Fix Arabic TextAlign.justify issues

### PR DESCRIPTION
**Pull request by Milad-Akarie**
Set default text align based on text direction
bump version up to 3.8.3

### CODE REVIEW

**Comment by Milad-Akarie** [comment]
The PR fixes this issue #1059

**Comment by VladL221** [comment]
Does this also fix it for Hebrew text as well? since both trl

**Comment by Milad-Akarie** [comment]
I haven't tested it on Hebru but it should work the same

**Comment by VladL221** [comment]
> I haven't tested it on Hebrew but it should work the same
Do you know when will the fix be released by any chance?

**Comment by DavBfr** [comment]
Merged, thanks!

**Pull request closed without merging**
