### PR TITLE
set PDFIUM_ARCH according to FLUTTER_TARGET_PLATFORM

### LINKED ISSUE #1448: Build fails on arm64 beacause of hardcoded target
Both flutter and pdfium openly support arm64 linux targets. 
In fact, if I change [this line](https://github.com/DavBfr/dart_pdf/blob/master/printing/linux/CMakeLists.txt#L20)  to be 
```
set(PDFIUM_ARCH "arm64" CACHE STRING "Architecture of pdfium used")
```
everything compiles correctly on the linux/arm64 target.

We should add a way to change the architecture programmatically.

**Desktop:**
 - [x] Linux - arm64

### PR DESCRIPTION
**Pull request by nik012003**
Should fix #1448

### CODE REVIEW

**Comment by nik012003** [comment]
oops, fixed the mistake. can you rerun it workflow?

**Comment by DavBfr** [comment]
Looks good. Maybe the same can be done for Windows.

**Comment by nik012003** [comment]
> Looks good. Maybe the same can be done for Windows.

Looks like that doesn't currently work on windows plaformts. See: [this issue](https://github.com/flutter/flutter/issues/116196)

**Comment by DavBfr** [comment]
Thanks!

**Comment by adil192** [comment]
@DavBfr Please can you release this to pub.dev

**Comment by adil192** [comment]
@DavBfr Any update?

**Pull request merged**
