### PR TITLE
fix: re-init UIPrinter cause issues with delegate

### PR DESCRIPTION
**Pull request by HasanAlqaisi**
Hi,

When we try using directPrintPdf with a specific format (let's say A4), it will be printed for the first time with no issues.

However, if you try to print again with the same format and the same printer, It will be printed with a different format.

After doing a long research, I found out that re-initializing the UIPrinter will cause this issue.

This is based on this link: [Airprint - background printing produces blanks pages
](https://developer.apple.com/forums/thread/722211)

The workaround is found in a comment that said:

> I would like to note that the workaround I have in place that appears to resolve this issue is to create and reuse a single instance of UIPrinter for all print jobs (so try creating a static shared singleton). It appears that recreating a Printer with the URL every job is causing issues with the delegate, leading to extra large printing.

The current implementation is recreating the UIPrinter each time we select one.

`let printer = UIPrinter(url: printerURL!)
`
Instead of doing this, we will save the selected printer in a global variable and then compare the printer URL with the one selected.

So if he tries to print again with the same printer, we won't init a new object and the issue will be resolved

### CODE REVIEW

**Comment by DavBfr** [comment]
Nice. Can you make `selectedPrinter` a map with the URL as the key instead? This way it will work even if the app prints to many printers.

**Comment by HasanAlqaisi** [comment]
> Nice. Can you make `selectedPrinter` a map with the URL as the key instead? This way it will work even if the app prints to many printers.

I got your point, I will give it a try soon and let you know,

**Comment by HasanAlqaisi** [comment]
> Nice. Can you make `selectedPrinter` a map with the URL as the key instead? This way it will work even if the app prints to many printers.

Done, can you check it please?

**Comment by DavBfr** [comment]
Thanks!

**Pull request merged**
