### PR TITLE
Revert "Apply THE BIDIRECTIONAL ALGORITHM using dart_bidi lib"

### PR DESCRIPTION
**Pull request by Baghdady92**
This reverts commit c497623dac54e5c822232be1180f0f0a8cf75306.
i had to disable bidi package to make arabic fonts work again 
btw the font hacen-tunisia.ttf working just fine with bidi 
but the other google fonts not all of them work 
i'm not sure what's the problem in bidi

### CODE REVIEW

**Comment by DavBfr** [comment]
Can we apply both Arabic and then Bidi for other RTL languages?

**Comment by Baghdady92** [comment]
yes i believe we can do both and make a property to select the working method for bidi or arabic that you provide in library 
for arabic everything work fine in RTL i'm not sure for other languages

**Comment by Milad-Akarie** [comment]
@Baghdady92 @DavBfr can we not revert this? I believe the issue is fixable, I'll do it my self as soon as I can.

**Comment by Milad-Akarie** [comment]
Hey @DavBfr  The result of the bidi algorithm seems to be correct, I strongly believe that the problem has to do with the cmap parsing algorithm as I followed the process of certain letters that don't render and it seems their glyphs do not exist in the parsed glyphs table. 
I don't know much about font parsing but maybe you could provide some guidance or a starting point for me to fix this issue.

**Comment by Milad-Akarie** [comment]
@Hey @DavBfr I managed to fix the issue where some Google fonts don't have glyphs for isolated Arabic letter forms, and it seems to work just fine, but after fixing the issue I've noticed that some fonts render diacritic improperly.


Screenshot 2023-07-24 at 7 23 33 PM

In the above example, I'm using the same font Cairo in both PDF and Google fonts, you can see how they're positioned correctly in google docs but not the generated PDF.

Any idea how to fix this? any pointers will help.

**Comment by Baghdady92** [comment]
with the latest update i tried once more about this 
and i notice some character in arabic are still wrong for example 
ي  and ى 
still wrong

**Comment by Baghdady92** [comment]
Add Support old Arabic method without bidi package 
We can add in future to use (useBidi or useArabic) method which suite the font requirement

**Pull request closed without merging**
