### PR TITLE
[printing] fix build issue with xcode 13.3 #977

### PR DESCRIPTION
**Pull request by cedteg**
at the moment I test this fix

you can test it via:

`printing: 
    git:
        url: https://github.com/cedteg/dart_pdf
        path: printing
`

### CODE REVIEW

**Comment by DavBfr** [comment]
All tests passed, can anyone test this? I don't have xcode 13.3

**Comment by cedteg** [comment]
I my case it fixed the above problem

But now i get this issue 
`[13:57:40]: ▸ [35m** ARCHIVE FAILED **[0m
[13:57:40]: ▸ [35mThe following build commands failed:[0m
[13:57:40]: ▸ [35m	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'printing' from project 'Pods')[0m
[13:57:40]: ▸ [35m	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'printing' from project 'Pods')[0m
[13:57:40]: ▸ [35m	SwiftCodeGeneration normal arm64 (in target 'printing' from project 'Pods')[0m
[13:57:40]: ▸ [35m(3 failures`

**Comment by regalmojo** [comment]
> path: printing

same here

**Comment by regalmojo** [comment]
@cedteg  initial issue is solved

But now i get this issue
[13:57:40]: ▸ �[35m** ARCHIVE FAILED **�[0m [13:57:40]: ▸ �[35mThe following build commands failed:�[0m [13:57:40]: ▸ �[35m CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'printing' from project 'Pods')�[0m [13:57:40]: ▸ �[35m CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'printing' from project 'Pods')�[0m [13:57:40]: ▸ �[35m SwiftCodeGeneration normal arm64 (in target 'printing' from project 'Pods')�[0m [13:57:40]: ▸ �[35m(3 failures

**Comment by DavBfr** [comment]
It's an Xcode crash: segfault. Nothing we can do...

**Comment by cedteg** [comment]
@DavBfr so merging this and waiting for the xcode 13.3.1 release?

**Comment by cedteg** [comment]
possible related to the new error
https://bugs.swift.org/plugins/servlet/mobile#issue/SR-15792

**Pull request merged**
