### PR TITLE
Added a boolean toggle to show/hide debug switch

### PR DESCRIPTION
**Pull request by bruntzcreative**
Looks like some formatting on unrelated code also happened, let me know if it's a problem.

### CODE REVIEW

**Comment by DavBfr** [comment]
Can you keep the assert? The debug switch will have no effect if asserts art not enabled. As in release build, so the switch should not show and not add extra code in this case.
Additionally, can you reformat the code with the default line length?

**Comment by DavBfr** [comment]
And if you can update the changelog too, that'd be perfect!

**Comment by bruntzcreative** [comment]
Sorry about the auto format here. Let me go tidy this up.

**Comment by DavBfr** [comment]
Merged, thanks!

**Pull request closed without merging**
