### PR TITLE
Fix Bidirectional text (Arabic + Latin words) order and line breakers issue 

### PR DESCRIPTION
**Pull request by Milad-Akarie**
This fixes this issue  #739  including proper handling of line breakers  in Bidirectional text

screenshot form the Arabic generated test pdf
Screen Shot 2022-03-30 at 4 49 27 PM

### CODE REVIEW

**Comment by DavBfr** [comment]
Looks good, thanks.
But space has been added to page 3 on the arabic.pdf test:

Screen Shot 2022-03-31 at 08 54 46

**Comment by DavBfr** [comment]
Merged, thanks!

**Comment by AkamBarznji** [comment]
Hello everyone, 

i got this problome ! i use Kurdish language 

[https://drive.google.com/file/d/1-f9ljOkvp9Vr7zoorMpuhM1iigRKtQS7/view?usp=sharing](url)

My words in kurdish language was damaged only in kurdish in arabic + English there's no issue!

for example one of words I selected in above pic is : شیوازی گەیاندن ١
٢-ژمارەی وەرگر

those images and every word in kurdish language was damaged !


Thanks for help

**Comment by DavBfr** [comment]
@Milad-Akarie yes I'll publish a version today.

**Comment by AkamBarznji** [comment]
**### Again Show me same error ! can you please look i have been updated all packages to last ...**

[https://imgur.com/a/cyGXoGQ](url)
https://imgur.com/a/cyGXoGQ
[https://i.imgur.com/5AoeWux.jpeg](url)



> Hello everyone,
> 
> i got this problome ! i use Kurdish language
> 
> https://drive.google.com/file/d/1-f9ljOkvp9Vr7zoorMpuhM1iigRKtQS7/view?usp=sharing
> 
> My words in kurdish language was damaged only in kurdish in arabic + English there's no issue!
> 
> for example one of words I selected in above pic is : شیوازی گەیاندن ١ ٢-ژمارەی وەرگر
> 
> those images and every word in kurdish language was damaged !
> 
> Thanks for help


آ

آگ

**Pull request closed without merging**
